# Generated by Django 2.2.17 on 2020-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('personality', models.CharField(choices=[('I', 'Inpulsivo'), ('E', 'Exigente'), ('C', 'Cauteloso'), ('A', 'Aleatório')], max_length=50, verbose_name='Personalidade')),
                ('purchase_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Saldo')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Jogadores',
                'verbose_name': 'Jogador',
            },
        ),
    ]
